"""moved_contract_address

Revision ID: 0ac0e12b0cdb
Revises: 4f628b3f93ef
Create Date: 2023-08-01 12:16:20.181118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ac0e12b0cdb'
down_revision = '4f628b3f93ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('contract_address', sa.VARCHAR(length=250), nullable=True))
    op.drop_column('token_pair', 'contract_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_pair', sa.Column('contract_address', mysql.VARCHAR(length=250), nullable=False))
    op.drop_column('token', 'contract_address')
    # ### end Alembic commands ###
