"""added_liquid_flag

Revision ID: 19c20537fdbb
Revises: 2fb551a5abe6
Create Date: 2024-09-14 10:48:08.659248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c20537fdbb'
down_revision = '2fb551a5abe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_pair', sa.Column('is_liquid', sa.BOOLEAN(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_pair', 'is_liquid')
    # ### end Alembic commands ###
