"""adding audit properties

Revision ID: 1f5a3a010dbe
Revises: 85a2dbb01e2d
Create Date: 2022-01-11 11:33:08.656934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f5a3a010dbe'
down_revision = '85a2dbb01e2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain',
                  sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('blockchain', sa.Column('created_by', sa.VARCHAR(length=50), nullable=False))
    op.add_column('blockchain', sa.Column('updated_at', sa.TIMESTAMP(),
                                          server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
                                          nullable=False))
    op.alter_column('blockchain', 'is_enabled',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.BOOLEAN(),
                    existing_nullable=True)
    op.add_column('conversion',
                  sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('conversion', sa.Column('created_by', sa.VARCHAR(length=50), nullable=False))
    op.add_column('conversion', sa.Column('updated_at', sa.TIMESTAMP(),
                                          server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
                                          nullable=False))
    op.add_column('conversion_fee',
                  sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('conversion_fee', sa.Column('created_by', sa.VARCHAR(length=50), nullable=False))
    op.add_column('conversion_fee', sa.Column('updated_at', sa.TIMESTAMP(),
                                              server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
                                              nullable=False))
    op.add_column('conversion_transaction',
                  sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('conversion_transaction', sa.Column('created_by', sa.VARCHAR(length=50), nullable=False))
    op.add_column('conversion_transaction', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text(
        'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('token',
                  sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('token', sa.Column('created_by', sa.VARCHAR(length=50), nullable=False))
    op.add_column('token', sa.Column('updated_at', sa.TIMESTAMP(),
                                     server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
                                     nullable=False))
    op.add_column('token_pair',
                  sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('token_pair', sa.Column('created_by', sa.VARCHAR(length=50), nullable=False))
    op.add_column('token_pair', sa.Column('updated_at', sa.TIMESTAMP(),
                                          server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
                                          nullable=False))
    op.alter_column('token_pair', 'is_enabled',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.BOOLEAN(),
                    existing_nullable=True)
    op.add_column('transaction',
                  sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('transaction', sa.Column('created_by', sa.VARCHAR(length=50), nullable=False))
    op.add_column('transaction', sa.Column('updated_at', sa.TIMESTAMP(),
                                           server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
                                           nullable=False))
    op.add_column('wallet_pair',
                  sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('wallet_pair', sa.Column('created_by', sa.VARCHAR(length=50), nullable=False))
    op.add_column('wallet_pair', sa.Column('updated_at', sa.TIMESTAMP(),
                                           server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
                                           nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet_pair', 'updated_at')
    op.drop_column('wallet_pair', 'created_by')
    op.drop_column('wallet_pair', 'created_at')
    op.drop_column('transaction', 'updated_at')
    op.drop_column('transaction', 'created_by')
    op.drop_column('transaction', 'created_at')
    op.alter_column('token_pair', 'is_enabled',
                    existing_type=sa.BOOLEAN(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=True)
    op.drop_column('token_pair', 'updated_at')
    op.drop_column('token_pair', 'created_by')
    op.drop_column('token_pair', 'created_at')
    op.drop_column('token', 'updated_at')
    op.drop_column('token', 'created_by')
    op.drop_column('token', 'created_at')
    op.drop_column('conversion_transaction', 'updated_at')
    op.drop_column('conversion_transaction', 'created_by')
    op.drop_column('conversion_transaction', 'created_at')
    op.drop_column('conversion_fee', 'updated_at')
    op.drop_column('conversion_fee', 'created_by')
    op.drop_column('conversion_fee', 'created_at')
    op.drop_column('conversion', 'updated_at')
    op.drop_column('conversion', 'created_by')
    op.drop_column('conversion', 'created_at')
    op.alter_column('blockchain', 'is_enabled',
                    existing_type=sa.BOOLEAN(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=True)
    op.drop_column('blockchain', 'updated_at')
    op.drop_column('blockchain', 'created_by')
    op.drop_column('blockchain', 'created_at')
    # ### end Alembic commands ###
