"""adding_deposit_addr_detail

Revision ID: 231a9abfb3b8
Revises: 4b9c0afa0a12
Create Date: 2022-03-07 13:04:37.620812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231a9abfb3b8'
down_revision = '4b9c0afa0a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_pair', sa.Column('deposit_address_detail', sa.JSON(), nullable=True))
    op.create_unique_constraint(None, 'wallet_pair', ['deposit_address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet_pair', type_='unique')
    op.drop_column('wallet_pair', 'deposit_address_detail')
    # ### end Alembic commands ###
