"""add_confirmation

Revision ID: 2a91ebf3c577
Revises: ff12eb1222b5
Create Date: 2022-03-11 11:29:39.317550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a91ebf3c577'
down_revision = 'ff12eb1222b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('confirmation', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'confirmation')
    # ### end Alembic commands ###
