"""remove_to_token_id

Revision ID: 45a2e7cd0d5d
Revises: 2a91ebf3c577
Create Date: 2022-03-25 00:45:20.055269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45a2e7cd0d5d'
down_revision = '2a91ebf3c577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('token_id', sa.BIGINT(), nullable=False))
    op.drop_constraint('transaction_ibfk_3', 'transaction', type_='foreignkey')
    op.drop_constraint('transaction_ibfk_2', 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'token', ['token_id'], ['row_id'])
    op.drop_column('transaction', 'from_token_id')
    op.drop_column('transaction', 'to_token_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('to_token_id', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('transaction', sa.Column('from_token_id', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key('transaction_ibfk_2', 'transaction', 'token', ['from_token_id'], ['row_id'])
    op.create_foreign_key('transaction_ibfk_3', 'transaction', 'token', ['to_token_id'], ['row_id'])
    op.drop_column('transaction', 'token_id')
    # ### end Alembic commands ###
