"""change_wallet_pair_constraint

Revision ID: 79c13150f688
Revises: 2a1db4eb72e3
Create Date: 2022-02-23 14:12:15.163652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79c13150f688'
down_revision = '2a1db4eb72e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('from_address', table_name='wallet_pair')
    op.create_unique_constraint(None, 'wallet_pair', ['token_pair_id', 'from_address', 'to_address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet_pair', type_='unique')
    op.create_index('from_address', 'wallet_pair', ['from_address', 'to_address'], unique=True)
    # ### end Alembic commands ###
