"""add_message_group_pool

Revision ID: b666d1766c3a
Revises: 45a2e7cd0d5d
Create Date: 2022-03-25 09:08:23.713110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b666d1766c3a'
down_revision = '45a2e7cd0d5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_group_pool',
    sa.Column('row_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('message_group_id', sa.VARCHAR(length=30), nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('row_id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('message_group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_group_pool')
    # ### end Alembic commands ###
