"""added_trading_view

Revision ID: e6dfb71c97ce
Revises: 19c20537fdbb
Create Date: 2025-01-16 20:47:52.983186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6dfb71c97ce'
down_revision = '19c20537fdbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_view',
    sa.Column('row_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=250), nullable=True),
    sa.Column('alt_text', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('row_id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('token', sa.Column('trading_view_id', sa.BIGINT(), nullable=True))
    op.create_foreign_key(None, 'token', 'trading_view', ['trading_view_id'], ['row_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token', type_='foreignkey')
    op.drop_column('token', 'trading_view_id')
    op.drop_table('trading_view')
    # ### end Alembic commands ###
