"""added_ada_thershold

Revision ID: f75df319b335
Revises: e6dfb71c97ce
Create Date: 2025-01-28 14:44:37.728102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f75df319b335'
down_revision = 'e6dfb71c97ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_pair', sa.Column('ada_threshold', sa.BIGINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_pair', 'ada_threshold')
    # ### end Alembic commands ###
