"""amount_not_null

Revision ID: ff12eb1222b5
Revises: 231a9abfb3b8
Create Date: 2022-03-10 00:44:09.210093

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff12eb1222b5'
down_revision = '231a9abfb3b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversion', 'claim_amount',
               existing_type=mysql.DECIMAL(precision=64, scale=0),
               nullable=False)
    op.alter_column('conversion', 'fee_amount',
               existing_type=mysql.DECIMAL(precision=64, scale=0),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversion', 'fee_amount',
               existing_type=mysql.DECIMAL(precision=64, scale=0),
               nullable=True)
    op.alter_column('conversion', 'claim_amount',
               existing_type=mysql.DECIMAL(precision=64, scale=0),
               nullable=True)
    # ### end Alembic commands ###
